packages:
  - packages/*

catalog:
  "@changesets/cli": ^2.29.8
  "@eslint/js": ^10.0.1
  "@eslint/markdown": ^7.5.1
  "@types/node": ^25.3.0
  eslint: ^9.39.2
  globals: ^17.3.0
  jiti: ^2.6.1
  lefthook: ^2.1.1
  tsx: ^4.7.0
  typescript: ^5.3.0
  typescript-eslint: ^8.56.0

catalogMode: strict
cleanupUnusedCatalogs: true
